CREATE TABLE IF NOT EXISTS funds (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    total_balance DECIMAL(18, 2) DEFAULT 0,
    clear_balance DECIMAL(18, 2) DEFAULT 0,
    available_balance DECIMAL(18, 2) DEFAULT 0,
    utilized_amount DECIMAL(18, 2) DEFAULT 0,
    realized_pnl DECIMAL(18, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS holdings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    exchange VARCHAR(50),
    quantity INT DEFAULT 0,
    avg_price DECIMAL(18, 4) DEFAULT 0,
    current_price DECIMAL(18, 4) DEFAULT 0,
    market_value DECIMAL(18, 4) DEFAULT 0,
    pnl DECIMAL(18, 4) DEFAULT 0,
    pnl_percent DECIMAL(5, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
