-- Update user_details table to include all Fyers profile attributes

ALTER TABLE user_details
ADD COLUMN IF NOT EXISTS name VARCHAR(255),
ADD COLUMN IF NOT EXISTS display_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS fy_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS image TEXT,
ADD COLUMN IF NOT EXISTS email_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS pan VARCHAR(10),
ADD COLUMN IF NOT EXISTS pin_change_date VARCHAR(50),
ADD COLUMN IF NOT EXISTS pwd_change_date VARCHAR(50),
ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(15),
ADD COLUMN IF NOT EXISTS totp BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pwd_to_expire INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS ddpi_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mtf_enabled BOOLEAN DEFAULT FALSE;
