FROM python:3.11-slim

WORKDIR /app

COPY data-ingestion-service/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY shared ./shared

COPY data-ingestion-service/ .

ENV POSTGRES_HOST=timescaledb
ENV POSTGRES_PORT=5432
ENV POSTGRES_USER=apiuser
ENV POSTGRES_PASSWORD=apipass
ENV POSTGRES_DB=stockmarket

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
