services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: aimstocks-api-gateway
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - USER_SERVICE_URL=http://user-service:8001
      - BROKER_SERVICE_URL=http://broker-service:8002
      - PORTFOLIO_SERVICE_URL=http://portfolio-service:8003
      - ORDER_SERVICE_URL=http://order-service:8004
      - MARKET_DATA_SERVICE_URL=http://market-data-service:8005
      - ALGORITHM_SERVICE_URL=http://algorithm-service:8006
      - ALERT_SERVICE_URL=http://alert-service:8007
      - NEWS_SERVICE_URL=http://news-service:8008
      - WEBSOCKET_SERVICE_URL=http://websocket-service:8009
      - DATA_INGESTION_SERVICE_URL=http://data-ingestion-service:8000
    depends_on:
      - user-service
      - broker-service
      - portfolio-service
      - order-service
      - market-data-service
      - algorithm-service
      - alert-service
      - news-service
      - websocket-service
      - data-ingestion-service
    networks:
      - aimstocks-network
